// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Domain.Models
{
    [Table("films_people_people")]
    [Index(nameof(FilmsId), Name = "IDX_b881b30fe31ea40ac371228bcd")]
    [Index(nameof(PeopleId), Name = "IDX_da2f86aa6b63734b057c04f41c")]
    public partial class FilmsPeoplePeople
    {
        [Key]
        [Column("filmsId")]
        public int FilmsId { get; set; }
        [Key]
        [Column("peopleId")]
        public int PeopleId { get; set; }

        [ForeignKey(nameof(FilmsId))]
        [InverseProperty("FilmsPeoplePeople")]
        public virtual Films Films { get; set; }
        [ForeignKey(nameof(PeopleId))]
        [InverseProperty("FilmsPeoplePeople")]
        public virtual People People { get; set; }
    }
}