// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Domain.Entities
{
    [Table("people_species_species")]
    [Index(nameof(SpeciesId), Name = "IDX_9232984d4ee14342ad97f44382")]
    [Index(nameof(PeopleId), Name = "IDX_d6d545e4740ee652e6f79e9ffd")]
    public partial class PeopleSpeciesSpecies
    {
        [Key]
        [Column("peopleId")]
        public int PeopleId { get; set; }
        [Key]
        [Column("speciesId")]
        public int SpeciesId { get; set; }

        [ForeignKey(nameof(PeopleId))]
        [InverseProperty("PeopleSpeciesSpecies")]
        public virtual People People { get; set; }
        [ForeignKey(nameof(SpeciesId))]
        [InverseProperty("PeopleSpeciesSpecies")]
        public virtual Species Species { get; set; }
    }
}