// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Domain.Entities
{
    [Table("planets_people_people")]
    [Index(nameof(PlanetsId), Name = "IDX_3f043ecf2a618410a25a1de60e")]
    [Index(nameof(PeopleId), Name = "IDX_eb823df3f9365cb64339400222")]
    public partial class PlanetsPeoplePeople
    {
        [Key]
        [Column("planetsId")]
        public int PlanetsId { get; set; }
        [Key]
        [Column("peopleId")]
        public int PeopleId { get; set; }

        [ForeignKey(nameof(PeopleId))]
        [InverseProperty("PlanetsPeoplePeople")]
        public virtual People People { get; set; }
        [ForeignKey(nameof(PlanetsId))]
        [InverseProperty("PlanetsPeoplePeople")]
        public virtual Planets Planets { get; set; }
    }
}