// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Domain.Entities
{
    [Table("starships_films_films")]
    [Index(nameof(StarshipsId), Name = "IDX_46d44d404f4456ffd9844b199b")]
    [Index(nameof(FilmsId), Name = "IDX_98f924110ceb5aea4d7378ab38")]
    public partial class StarshipsFilmsFilms
    {
        [Key]
        [Column("starshipsId")]
        public int StarshipsId { get; set; }
        [Key]
        [Column("filmsId")]
        public int FilmsId { get; set; }

        [ForeignKey(nameof(FilmsId))]
        [InverseProperty("StarshipsFilmsFilms")]
        public virtual Films Films { get; set; }
        [ForeignKey(nameof(StarshipsId))]
        [InverseProperty("StarshipsFilmsFilms")]
        public virtual Starships Starships { get; set; }
    }
}