// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Domain.Models
{
    [Table("vehicles_people_people")]
    [Index(nameof(VehiclesId), Name = "IDX_85b97aff3b9b8128311bb5284e")]
    [Index(nameof(PeopleId), Name = "IDX_96a94e6f0bb28e7880094f2cee")]
    public partial class VehiclesPeoplePeople
    {
        [Key]
        [Column("vehiclesId")]
        public int VehiclesId { get; set; }
        [Key]
        [Column("peopleId")]
        public int PeopleId { get; set; }

        [ForeignKey(nameof(PeopleId))]
        [InverseProperty("VehiclesPeoplePeople")]
        public virtual People People { get; set; }
        [ForeignKey(nameof(VehiclesId))]
        [InverseProperty("VehiclesPeoplePeople")]
        public virtual Vehicles Vehicles { get; set; }
    }
}