// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Models
{
    [Table("species_films_films")]
    [Index(nameof(SpeciesId), Name = "IDX_15037e69b396f7e73bc515265a")]
    [Index(nameof(FilmsId), Name = "IDX_1bb7bf460101ed61435f7f806b")]
    public partial class SpeciesFilmsFilms
    {
        [Key]
        [Column("speciesId")]
        public int SpeciesId { get; set; }
        [Key]
        [Column("filmsId")]
        public int FilmsId { get; set; }

        [ForeignKey(nameof(FilmsId))]
        [InverseProperty("SpeciesFilmsFilms")]
        public virtual Films Films { get; set; }
        [ForeignKey(nameof(SpeciesId))]
        [InverseProperty("SpeciesFilmsFilms")]
        public virtual Species Species { get; set; }
    }
}