// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Models
{
    [Table("starships_people_people")]
    [Index(nameof(PeopleId), Name = "IDX_18a1bb6f5e950770f28586659b")]
    [Index(nameof(StarshipsId), Name = "IDX_1911c83a74aeb1af7ad576b5bd")]
    public partial class StarshipsPeoplePeople
    {
        [Key]
        [Column("starshipsId")]
        public int StarshipsId { get; set; }
        [Key]
        [Column("peopleId")]
        public int PeopleId { get; set; }

        [ForeignKey(nameof(PeopleId))]
        [InverseProperty("StarshipsPeoplePeople")]
        public virtual People People { get; set; }
        [ForeignKey(nameof(StarshipsId))]
        [InverseProperty("StarshipsPeoplePeople")]
        public virtual Starships Starships { get; set; }
    }
}