// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Models
{
    [Table("vehicles")]
    [Index(nameof(Name), Name = "IDX_aa397b791341ed3615397050d4", IsUnique = true)]
    public partial class Vehicles
    {
        public Vehicles()
        {
            FilmsVehiclesVehicles = new HashSet<FilmsVehiclesVehicles>();
            PeopleVehiclesVehicles = new HashSet<PeopleVehiclesVehicles>();
            VehiclesFilmsFilms = new HashSet<VehiclesFilmsFilms>();
            VehiclesPeoplePeople = new HashSet<VehiclesPeoplePeople>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name", TypeName = "varchar(200)")]
        public string Name { get; set; }
        [Required]
        [Column("model", TypeName = "varchar(200)")]
        public string Model { get; set; }
        [Required]
        [Column("vehicle_class", TypeName = "varchar(200)")]
        public string VehicleClass { get; set; }
        [Required]
        [Column("manufacturer", TypeName = "varchar(200)")]
        public string Manufacturer { get; set; }
        [Required]
        [Column("length", TypeName = "varchar(200)")]
        public string Length { get; set; }
        [Required]
        [Column("cost_in_credits", TypeName = "varchar(200)")]
        public string CostInCredits { get; set; }
        [Required]
        [Column("crew", TypeName = "varchar(200)")]
        public string Crew { get; set; }
        [Required]
        [Column("passengers", TypeName = "varchar(200)")]
        public string Passengers { get; set; }
        [Required]
        [Column("max_atmosphering_speed", TypeName = "varchar(200)")]
        public string MaxAtmospheringSpeed { get; set; }
        [Required]
        [Column("cargo_capacity", TypeName = "varchar(200)")]
        public string CargoCapacity { get; set; }
        [Required]
        [Column("consumables", TypeName = "varchar(200)")]
        public string Consumables { get; set; }
        [Required]
        [Column("url", TypeName = "varchar(200)")]
        public string Url { get; set; }
        [Required]
        [Column("created", TypeName = "varchar(30)")]
        public string Created { get; set; }
        [Required]
        [Column("edited", TypeName = "varchar(30)")]
        public string Edited { get; set; }

        [InverseProperty("Vehicles")]
        public virtual ICollection<FilmsVehiclesVehicles> FilmsVehiclesVehicles { get; set; }
        [InverseProperty("Vehicles")]
        public virtual ICollection<PeopleVehiclesVehicles> PeopleVehiclesVehicles { get; set; }
        [InverseProperty("Vehicles")]
        public virtual ICollection<VehiclesFilmsFilms> VehiclesFilmsFilms { get; set; }
        [InverseProperty("Vehicles")]
        public virtual ICollection<VehiclesPeoplePeople> VehiclesPeoplePeople { get; set; }
    }
}