// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using System.Text.Json.Serialization;


#nullable disable

namespace LukeSkywalker.Domain.Entities
{
    [Table("films")]
    [Index(nameof(Title), Name = "IDX_ef6e0245decf772d1dd66f158a", IsUnique = true)]
    public partial class Films
    {
        public Films()
        {
            FilmsPeoplePeople = new HashSet<FilmsPeoplePeople>();
            FilmsPlanetsPlanets = new HashSet<FilmsPlanetsPlanets>();
            FilmsSpeciesSpecies = new HashSet<FilmsSpeciesSpecies>();
            FilmsStarshipsStarships = new HashSet<FilmsStarshipsStarships>();
            FilmsVehiclesVehicles = new HashSet<FilmsVehiclesVehicles>();
            PeopleFilmsFilms = new HashSet<PeopleFilmsFilms>();
            PlanetsFilmsFilms = new HashSet<PlanetsFilmsFilms>();
            SpeciesFilmsFilms = new HashSet<SpeciesFilmsFilms>();
            StarshipsFilmsFilms = new HashSet<StarshipsFilmsFilms>();
            VehiclesFilmsFilms = new HashSet<VehiclesFilmsFilms>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("title", TypeName = "varchar(200)")]
        public string Title { get; set; }
        [Column("opening_crawl", TypeName = "varchar(1000)")]
        public string OpeningCrawl { get; set; }
        [Column("director", TypeName = "varchar(200)")]
        public string Director { get; set; }
        [Column("producer", TypeName = "varchar(200)")]
        public string Producer { get; set; }
        [Column("release_date", TypeName = "varchar(255)")]
        public string ReleaseDate { get; set; }
        [Column("url", TypeName = "varchar(500)")]
        public string Url { get; set; }
        [Column("created", TypeName = "varchar(30)")]
        public string Created { get; set; }
        [Column("edited", TypeName = "varchar(30)")]
        public string Edited { get; set; }
        [Column("episode_id")]
        public int EpisodeId { get; set; }

        [InverseProperty("Films")]
        [JsonIgnore]
        public virtual ICollection<FilmsPeoplePeople> FilmsPeoplePeople { get; set; }
        [InverseProperty("Films")]
        [JsonIgnore]
        public virtual ICollection<FilmsPlanetsPlanets> FilmsPlanetsPlanets { get; set; }
        [InverseProperty("Films")]
        [JsonIgnore]
        public virtual ICollection<FilmsSpeciesSpecies> FilmsSpeciesSpecies { get; set; }
        [InverseProperty("Films")]
        [JsonIgnore]
        public virtual ICollection<FilmsStarshipsStarships> FilmsStarshipsStarships { get; set; }
        [InverseProperty("Films")]
        [JsonIgnore]
        public virtual ICollection<FilmsVehiclesVehicles> FilmsVehiclesVehicles { get; set; }
        [InverseProperty("Films")]
        [JsonIgnore]
        public virtual ICollection<PeopleFilmsFilms> PeopleFilmsFilms { get; set; }
        [InverseProperty("Films")]
        [JsonIgnore]
        public virtual ICollection<PlanetsFilmsFilms> PlanetsFilmsFilms { get; set; }
        [InverseProperty("Films")]
        [JsonIgnore]
        public virtual ICollection<SpeciesFilmsFilms> SpeciesFilmsFilms { get; set; }
        [InverseProperty("Films")]
        [JsonIgnore]
        public virtual ICollection<StarshipsFilmsFilms> StarshipsFilmsFilms { get; set; }
        [InverseProperty("Films")]
        [JsonIgnore]
        public virtual ICollection<VehiclesFilmsFilms> VehiclesFilmsFilms { get; set; }
    }
}