// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using System.Text.Json.Serialization;

#nullable disable

namespace LukeSkywalker.Domain.Entities
{
    [Table("starships")]
    [Index(nameof(Name), Name = "IDX_41580e76da7903fb3827a3510e", IsUnique = true)]
    public partial class Starships
    {
        public Starships()
        {
            FilmsStarshipsStarships = new HashSet<FilmsStarshipsStarships>();
            PeopleStarshipsStarships = new HashSet<PeopleStarshipsStarships>();
            StarshipsFilmsFilms = new HashSet<StarshipsFilmsFilms>();
            StarshipsPeoplePeople = new HashSet<StarshipsPeoplePeople>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name", TypeName = "varchar(200)")]
        public string Name { get; set; }
        [Column("model", TypeName = "varchar(200)")]
        public string Model { get; set; }
        [Column("starship_class", TypeName = "varchar(200)")]
        public string StarshipClass { get; set; }
        [Column("manufacturer", TypeName = "varchar(200)")]
        public string Manufacturer { get; set; }
        [Column("cost_in_credits", TypeName = "varchar(200)")]
        public string CostInCredits { get; set; }
        [Column("length", TypeName = "varchar(200)")]
        public string Length { get; set; }
        [Column("crew", TypeName = "varchar(200)")]
        public string Crew { get; set; }
        [Column("passengers", TypeName = "varchar(200)")]
        public string Passengers { get; set; }
        [Column("max_atmosphering_speed", TypeName = "varchar(200)")]
        public string MaxAtmospheringSpeed { get; set; }
        [Column("hyperdrive_rating", TypeName = "varchar(200)")]
        public string HyperdriveRating { get; set; }
        [Column("MGLT", TypeName = "varchar(200)")]
        public string Mglt { get; set; }
        [Column("cargo_capacity", TypeName = "varchar(200)")]
        public string CargoCapacity { get; set; }
        [Column("consumables", TypeName = "varchar(200)")]
        public string Consumables { get; set; }
        [Column("url", TypeName = "varchar(200)")]
        public string Url { get; set; }
        [Column("created", TypeName = "varchar(30)")]
        public string Created { get; set; }
        [Column("edited", TypeName = "varchar(30)")]
        public string Edited { get; set; }

        [InverseProperty("Starships")]
        [JsonIgnore]
        public virtual ICollection<FilmsStarshipsStarships> FilmsStarshipsStarships { get; set; }
        [InverseProperty("Starships")]
        [JsonIgnore]
        public virtual ICollection<PeopleStarshipsStarships> PeopleStarshipsStarships { get; set; }
        [InverseProperty("Starships")]
        [JsonIgnore]
        public virtual ICollection<StarshipsFilmsFilms> StarshipsFilmsFilms { get; set; }
        [InverseProperty("Starships")]
        [JsonIgnore]
        public virtual ICollection<StarshipsPeoplePeople> StarshipsPeoplePeople { get; set; }
    }
}