powershell Invoke-WebRequest http://localhost:4000/api/film/pull
powershell Invoke-WebRequest http://localhost:4000/api/people/pull
powershell Invoke-WebRequest http://localhost:4000/api/planet/pull
powershell Invoke-WebRequest http://localhost:4000/api/vehicle/pull
powershell Invoke-WebRequest http://localhost:4000/api/specie/pull
powershell Invoke-WebRequest http://localhost:4000/api/starship/pull
powershell Invoke-WebRequest http://localhost:4000/api/film/pull/relations
powershell Invoke-WebRequest http://localhost:4000/api/people/pull/relations
powershell Invoke-WebRequest http://localhost:4000/api/planet/pull/relations
powershell Invoke-WebRequest http://localhost:4000/api/vehicle/pull/relations
powershell Invoke-WebRequest http://localhost:4000/api/specie/pull/relations
powershell Invoke-WebRequest http://localhost:4000/api/starship/pull/relations