// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Models
{
    [Table("films_species_species")]
    [Index(nameof(SpeciesId), Name = "IDX_6042e3f9819bb64e4264509f73")]
    [Index(nameof(FilmsId), Name = "IDX_be1d816ce6bdc4677080067eb4")]
    public partial class FilmsSpeciesSpecies
    {
        [Key]
        [Column("filmsId")]
        public int FilmsId { get; set; }
        [Key]
        [Column("speciesId")]
        public int SpeciesId { get; set; }

        [ForeignKey(nameof(FilmsId))]
        [InverseProperty("FilmsSpeciesSpecies")]
        public virtual Films Films { get; set; }
        [ForeignKey(nameof(SpeciesId))]
        [InverseProperty("FilmsSpeciesSpecies")]
        public virtual Species Species { get; set; }
    }
}