// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Models
{
    [Table("people_vehicles_vehicles")]
    [Index(nameof(PeopleId), Name = "IDX_a7b8cbe95c602d58ade9845ce6")]
    [Index(nameof(VehiclesId), Name = "IDX_f872d6f9465604601135f41970")]
    public partial class PeopleVehiclesVehicles
    {
        [Key]
        [Column("peopleId")]
        public int PeopleId { get; set; }
        [Key]
        [Column("vehiclesId")]
        public int VehiclesId { get; set; }

        [ForeignKey(nameof(PeopleId))]
        [InverseProperty("PeopleVehiclesVehicles")]
        public virtual People People { get; set; }
        [ForeignKey(nameof(VehiclesId))]
        [InverseProperty("PeopleVehiclesVehicles")]
        public virtual Vehicles Vehicles { get; set; }
    }
}