// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LukeSkywalker.Models
{
    [Table("people_films_films")]
    [Index(nameof(FilmsId), Name = "IDX_80ce66926f5e215472c235a3a6")]
    [Index(nameof(PeopleId), Name = "IDX_be3d4bf0a2a829c091594359de")]
    public partial class PeopleFilmsFilms
    {
        [Key]
        [Column("peopleId")]
        public int PeopleId { get; set; }
        [Key]
        [Column("filmsId")]
        public int FilmsId { get; set; }

        [ForeignKey(nameof(FilmsId))]
        [InverseProperty("PeopleFilmsFilms")]
        public virtual Films Films { get; set; }
        [ForeignKey(nameof(PeopleId))]
        [InverseProperty("PeopleFilmsFilms")]
        public virtual People People { get; set; }
    }
}